on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
      - name: Instalar dependencias
        run: npm install
      - name: Compilar y probar
        run: npm run build && npm test
      - name: Publicar en npm
        run: npm publish